---
id: theme-benchmark-ja
tags:
- rabbit
base_name: theme-benchmark
presentation_date: 
version: 1.0.3
licenses:
- GPLv3+
- GFDL
- CC BY-SA 3.0
author:
  markup_language: :rd
  name: Rabbit
  email: lavie@rabbit-shocker.org
  rubygems_user: rabbit
  slideshare_user: 
  speaker_deck_user: 
